baseURL = "https://tuxnode.github.io/"
title = "Geek's Tech Base"
paginate = 5
theme = "hugo-coder"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

[params]
  env = "production"
  title = "My Code Sandbox"
  description = "Low-level systems, computer architecture, and security research"
  colorScheme = "dark"
  author = "TuxNode"
  info = "Low-level systems & security"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tuxnode"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 2
  url = "mailto:tuxnode@outlook.com"

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20
