baseURL = "https://tuxnode.fun/"
title = "Geek's Tech Base"
languageCode = "zh-CN"
theme = "digio-theme"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

  [markup.goldmark.extensions.passthrough]
    enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)'], ['$', '$']]

[params]
  env = "production"
  description = "Low-level systems, computer architecture, and security research"
  email = "tuxnode@outlook.com"

  [params.giscus]
    repo = "tuxnode/tuxnode.github.io"
    repoId = "R_kgDOSubkiQ"
    category = "Q&A"
    categoryId = "DIC_kwDOSubkic4C_i3p"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1
    [menus.main.params]
      image = '/digigarden2025.png'

  [[menus.main]]
    name = 'posts'
    pageRef = '/posts'
    weight = 2

  [[menus.main]]
    name = 'me'
    pageRef = '/me'
    weight = 3

  [[menus.main]]
    name = 'friends'
    pageRef = '/friends'
    weight = 4
